language: php
php:
  - '7.1'
#services:
#  - mysql
#addons:
#  apt:
#    sources:
#      - mysql-5.7-trusty
#    packages:
#      - mysql-server
install:
  - composer install
  - cp .env.example .env
  - touch database/database.sqlite
  - php artisan key:generate
  - php artisan migrate
#cache:
#  directories:
#    - node_modules
#    - vendor